[package]
name = "shell-rs"
version = "0.1.0"
authors = ["spacedome <julien@spacedome.tv>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
nom = "7.1.3"
thiserror = "1.0.38"
